<script lang="ts">
  import { Menu, X, Search, Bell, Code2, BrainCircuit, Building2, BookOpen, Home } from 'lucide-svelte';
  import { page } from '$app/stores';
  let { children } = $props(); let open = $state(false);
  const items = [{ label: 'Overview', href: '/', icon: Home }, { label: 'DSA', href: '/dsa', icon: Code2 }, { label: 'Aptitude', href: '/aptitude', icon: BrainCircuit }, { label: 'Reasoning', href: '/reasoning', icon: BrainCircuit }, { label: 'Technical MCQ', href: '/mcq', icon: BookOpen }, { label: 'Companies', href: '/companies', icon: Building2 }];
</script>
<div class="min-h-screen bg-[#fcfbfa] text-text-primary"><header class="sticky top-0 z-50 flex h-16 items-center justify-between border-b border-border/60 bg-[#fcfbfa]/90 px-4 backdrop-blur-xl lg:hidden"><button onclick={() => open = !open} aria-label="Toggle navigation" class="grid h-10 w-10 place-items-center rounded-xl hover:bg-secondary-background">{#if open}<X size={19}/>{:else}<Menu size={19}/>{/if}</button><a href="/" class="font-extrabold tracking-tight">Placement<span class="text-primary">Pro</span></a><button class="grid h-10 w-10 place-items-center rounded-xl hover:bg-secondary-background"><Search size={18}/></button></header>
  <aside class="fixed inset-y-0 left-0 z-40 hidden w-[232px] border-r border-border/60 bg-[#fcfbfa] p-4 lg:flex lg:flex-col"><a href="/" class="flex h-12 items-center gap-3 px-2 font-extrabold tracking-tight"><span class="grid h-8 w-8 place-items-center rounded-xl bg-text-primary text-sm text-white">P</span> PlacementPro</a><nav class="mt-8 space-y-1">{#each items as item}<a href={item.href} class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition {$page.url.pathname === item.href || (item.href !== '/' && $page.url.pathname.startsWith(item.href)) ? 'bg-secondary-background text-text-primary' : 'text-text-secondary hover:bg-secondary-background/60 hover:text-text-primary'}"><svelte:component this={item.icon} size={17} class={$page.url.pathname.startsWith(item.href) && item.href !== '/' ? 'text-primary' : ''}/>{item.label}</a>{/each}</nav><div class="mt-auto rounded-2xl bg-[#17202b] p-4 text-white"><p class="text-xs font-bold text-orange-200">DAILY GOAL</p><p class="mt-3 text-sm font-bold">2 problems left</p><div class="mt-3 h-1.5 rounded-full bg-white/15"><div class="h-full w-2/3 rounded-full bg-primary"></div></div></div></aside>
  {#if open}<div class="fixed inset-x-0 top-16 z-40 border-b border-border bg-[#fcfbfa] p-4 shadow-xl lg:hidden"><nav class="grid grid-cols-2 gap-2">{#each items as item}<a onclick={() => open = false} href={item.href} class="flex items-center gap-2 rounded-xl bg-secondary-background/60 p-3 text-sm font-bold"><svelte:component this={item.icon} size={16}/>{item.label}</a>{/each}</nav></div>{/if}
  <div class="lg:pl-[232px]"><div class="hidden h-16 items-center justify-end gap-3 border-b border-border/60 px-8 lg:flex"><button class="flex h-9 w-64 items-center gap-2 rounded-xl bg-secondary-background/70 px-3 text-left text-xs text-text-secondary"><Search size={15}/> Search everything <kbd class="ml-auto">⌘K</kbd></button><button class="grid h-9 w-9 place-items-center rounded-xl hover:bg-secondary-background"><Bell size={17}/></button><div class="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-primary to-orange-300 text-xs font-bold text-white">AS</div></div><main class="min-h-[calc(100vh-4rem)]">{@render children()}</main></div>
</div>
