<script lang="ts">
  import { Flame, Trophy, Search, ArrowRight, Code2, Bookmark, CircleCheck, Sparkles } from 'lucide-svelte';
  import { neetcode150 } from '$lib/data/dsa';
  import QuestionCard from '$lib/components/placement/QuestionCard.svelte';
  let query = ''; let active = 'All';
  const topics = ['Arrays & Hashing', 'Two Pointers', 'Sliding Window', 'Stack', 'Binary Search', 'Linked List', 'Trees', 'Graphs', 'Dynamic Programming'];
  $: filtered = neetcode150.filter(q => (!query || q.title.toLowerCase().includes(query.toLowerCase())) && (active === 'All' || q.category === active));
</script>

<div class="mx-auto max-w-7xl px-4 py-7 md:px-8 md:py-10">
  <section class="relative overflow-hidden rounded-[2rem] bg-[#17202b] px-6 py-8 text-white shadow-2xl md:px-10 md:py-10">
    <div class="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-primary/30 blur-3xl"></div><div class="absolute bottom-0 left-1/3 h-40 w-72 rounded-full bg-accent/30 blur-3xl"></div>
    <div class="relative grid gap-8 lg:grid-cols-[1.35fr_.85fr]"><div><div class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold text-orange-100"><Sparkles size={13}/> Your interview operating system</div><h1 class="mt-5 max-w-xl text-3xl font-extrabold leading-tight md:text-5xl">Build instincts that hold up under pressure.</h1><p class="mt-4 max-w-xl text-sm leading-6 text-slate-300">A focused DSA workspace with the NeetCode 150, deliberate practice paths, and progress that makes your next interview feel earned.</p><div class="relative mt-6 max-w-xl"><Search size={18} class="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input bind:value={query} placeholder="Search all 150 questions..." class="w-full rounded-2xl border border-white/10 bg-white px-11 py-4 text-sm text-text-primary outline-none ring-primary focus:ring-2"/></div></div>
      <div class="grid grid-cols-2 gap-3 self-end"><div class="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><Flame class="text-orange-300" size={21}/><p class="mt-5 text-2xl font-extrabold">12 days</p><p class="text-xs text-slate-300">Current streak</p></div><div class="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><Trophy class="text-yellow-300" size={21}/><p class="mt-5 text-2xl font-extrabold">2,480</p><p class="text-xs text-slate-300">XP earned</p></div><div class="col-span-2 rounded-2xl border border-white/10 bg-white/10 p-4"><div class="flex items-center justify-between text-xs text-slate-300"><span>NeetCode 150 progress</span><span>32 / 150</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full w-[21%] rounded-full bg-gradient-to-r from-primary to-orange-300"></div></div></div></div></div>
  </section>
  <section class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl border border-border/70 bg-white p-5 shadow-card"><CircleCheck class="text-emerald-500"/><p class="mt-4 text-2xl font-extrabold">32</p><p class="text-xs text-text-secondary">Questions solved</p></div><div class="rounded-2xl border border-border/70 bg-white p-5 shadow-card"><Bookmark class="text-primary"/><p class="mt-4 text-2xl font-extrabold">18</p><p class="text-xs text-text-secondary">Saved for later</p></div><div class="rounded-2xl border border-border/70 bg-white p-5 shadow-card"><Code2 class="text-accent"/><p class="mt-4 text-2xl font-extrabold">4 / 9</p><p class="text-xs text-text-secondary">Topics in motion</p></div><a href="/dsa/question/{neetcode150[32].slug}" class="rounded-2xl bg-secondary-background p-5 transition hover:bg-secondary hover:shadow-card"><p class="text-xs font-bold uppercase tracking-wider text-primary">Continue learning</p><p class="mt-3 font-bold">{neetcode150[32].title}</p><span class="mt-4 inline-flex items-center gap-1 text-xs font-bold text-primary">Resume <ArrowRight size={14}/></span></a></section>
  <section class="mt-10"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-primary">The core path</p><h2 class="mt-2 text-2xl font-extrabold">NeetCode 150</h2></div><a href="#questions" class="text-sm font-bold text-primary">View all questions →</a></div><div class="mt-5 flex gap-2 overflow-x-auto pb-1">{#each ['All', ...topics] as topic}<button onclick={() => active = topic} class="whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold transition {active === topic ? 'bg-text-primary text-white' : 'border border-border bg-white text-text-secondary hover:border-primary'}">{topic}</button>{/each}</div></section>
  <section id="questions" class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{#each filtered.slice(0, 18) as question}<QuestionCard {question}/>{/each}</section>
  <section class="mt-12 grid gap-4 md:grid-cols-3">{#each ['Blind 75', 'Topic-wise practice', 'Company-wise rounds'] as title, i}<a href={i === 2 ? '/companies' : '/dsa'} class="group rounded-3xl border border-border/70 bg-white p-6 shadow-card transition hover:-translate-y-1 hover:shadow-card-hover"><p class="text-xs font-bold uppercase tracking-wider text-primary">Curated path</p><h3 class="mt-8 text-xl font-extrabold">{title}</h3><p class="mt-2 text-sm text-text-secondary">A deliberate route with the right level of repetition.</p><ArrowRight class="mt-5 transition group-hover:translate-x-1" size={18}/></a>{/each}</section>
</div>
