<script lang="ts">
  import { ArrowRight, Calendar, CheckCircle2, Sparkles, UsersRound } from 'lucide-svelte';
  import { mentors } from '$lib/data/mentors';
</script>
<svelte:head><title>Mentors · PlacementPro</title></svelte:head>
<div class="mx-auto max-w-7xl px-4 py-8 md:px-8 md:py-12">
  <section class="relative overflow-hidden rounded-[2rem] bg-[#17202b] px-6 py-10 text-white md:px-12 md:py-14"><div class="absolute -right-20 -top-24 h-80 w-80 rounded-full bg-primary/25 blur-3xl"></div><div class="relative max-w-3xl"><p class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-orange-100"><Sparkles size={14}/> Human guidance for the hard parts</p><h1 class="mt-5 text-4xl font-extrabold leading-tight md:text-6xl">You don’t need more content. You need the right conversation.</h1><p class="mt-5 max-w-2xl text-sm leading-7 text-slate-300 md:text-base">Meet mentors who have been through the placement loop. Get an honest review of your plan, resume, and interview stories.</p><div class="mt-8 flex flex-wrap gap-3"><a href="#mentor-list" class="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-[#17202b]">Meet the team <ArrowRight size={16}/></a><span class="inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold text-slate-200"><UsersRound size={16}/> {mentors.length} mentors</span></div></div></section>
  <section id="mentor-list" class="mt-12"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-primary">The mentor circle</p><h2 class="mt-2 text-3xl font-extrabold">Find a perspective that fits your next step.</h2></div><p class="text-sm text-text-secondary">Sessions are currently placeholder bookings.</p></div><div class="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{#each mentors as mentor}<article class="group overflow-hidden rounded-3xl bg-white shadow-card transition duration-300 hover:-translate-y-1.5 hover:shadow-card-hover"><div class="h-2 bg-gradient-to-r {mentor.tone}"></div><div class="p-6"><div class="flex items-start justify-between gap-4"><div class="grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br {mentor.tone} text-lg font-black text-white shadow-lg">{mentor.initials}</div><span class="rounded-full bg-secondary-background px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-text-secondary">{mentor.badge}</span></div><h3 class="mt-6 text-xl font-extrabold">{mentor.name}</h3><p class="mt-2 min-h-12 text-sm leading-6 text-text-secondary">{mentor.bio}</p><div class="mt-5 flex flex-wrap gap-2">{#each mentor.expertise as skill}<span class="rounded-lg bg-[#f7f5f3] px-2.5 py-1.5 text-[11px] font-semibold text-text-secondary">{skill}</span>{/each}</div><div class="mt-6 border-t border-border/70 pt-5"><p class="text-xs font-bold uppercase tracking-wider text-text-secondary">Experience across</p><p class="mt-2 text-sm font-bold">{mentor.offers.join(' · ')}</p></div><div class="mt-6 flex gap-2"><a href="/mentors/{mentor.slug}" class="flex-1 rounded-xl bg-text-primary px-3 py-3 text-center text-xs font-bold text-white transition hover:bg-primary">View profile</a><button class="inline-flex items-center gap-1 rounded-xl border border-border px-3 py-3 text-xs font-bold transition hover:border-primary hover:text-primary"><Calendar size={14}/> Book</button></div></div></article>{/each}</div></section>
  <section class="mt-14 rounded-3xl border border-border bg-secondary-background/60 p-7 md:flex md:items-center md:justify-between"><div><p class="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><CheckCircle2 size={15}/> A focused session</p><h2 class="mt-3 text-2xl font-extrabold">Bring one real question.</h2><p class="mt-2 max-w-xl text-sm leading-6 text-text-secondary">A resume bullet, interview answer, DSA topic, or project decision. The best sessions start with something concrete.</p></div><a href="#mentor-list" class="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary md:mt-0">Choose a mentor <ArrowRight size={16}/></a></section>
</div>
